@startuml Retour
scale 600*600
hide footbox

Emetteur -> Serveur: envoi(message, destinataireId)
Serveur -> Serveur: trouveDestinataire(destinataireId)
alt destinataire trouvé
Serveur -> Destinataire: envoi(message)
Destinataire -> Serveur: message reçu
Serveur -> Emetteur: message reçu
else destinataire n'existe pas
Serveur -> Emetteur: pas de destinataire
end
@enduml