@startuml extension
scale 400*400

MyParentClass <|-- MyClass1
MyParentClass <|-- MyClass2

class MyParentClass {
  -Object: parentPrivateField
  +DoSomethingForAll()
}

class MyClass1 {
 -Object: myPrivateField
 +Object: myPublicField
 ~DoSomethingForMe()
 +DoSomethingForAll()
}

class MyClass2 {
 -Object: myPrivateField
 +Object: myPublicField
 ~DoSomethingForMe()
 +DoSomethingForAll()
}
@enduml