@startuml sequence

-> SalleMusique : AjoutMusique(Musique musique)
SalleMusique -> ValidateurDeMusique : ValideMusique(Musique musique)
SalleMusique <- ValidateurDeMusique : validation
alt morceau validé
    SalleMusique -> MusiquePlayer : Joue(Musique musique)
else
<- SalleMusique: morceau rejeté
end

@enduml
