@startuml exercice-ocp-correction
scale 600*600
hide footbox

class Vendor{
    sell()
}

class Customer {
    int: age
}

interface CustomerAgeValidator{
    isOldEnoughToBuyAlcohol(int age)
}

class FRAgeValidator{
    isOldEnoughToBuyAlcohol(int age)
}

class USAgeValidator{
    isOldEnoughToBuyAlcohol(int age)
}

Customer --> Vendor
Vendor o- CustomerAgeValidator
CustomerAgeValidator <|.. FRAgeValidator
CustomerAgeValidator <|.. USAgeValidator
@enduml