@startuml exercice-isp
scale 600*600
hide footbox

class Vehicle {
    startEngine()
    turnLightsOn()
}

class VehicleLightTurner  {
    Vehicle: Vehicle
    turnOnTheLights()
}

Vehicle -o VehicleLightTurner

@enduml