@startuml isp
scale 600*600
hide footbox

Interface IWorker{
    work()
    eat()
    sleep()
}

class HumanWorker {
    work()
    eat()
    sleep()
}

class RobotWorker {
    work()
    eat()
    sleep()
}
note left: eat and sleep are not relevant

IWorker <|-- HumanWorker
IWorker <|-- RobotWorker
@enduml