@startuml lsp
scale 400*400
hide footbox

class Duck{
    fly()
}

class ElectricDuck{
    fly()
    turnOn()
    turnOff()
}

class Pond{
    runDuckFly()
}


Pond --o Duck
ElectricDuck -|> Duck

@enduml