@startuml abstraite
scale 600*600

class Conducteur {
    + avance(Vehicule vehicule)
}

abstract class Vehicule {
    + void roule()
    + void changeDirection(Direction direction)
    - void seConnectALArbreDeTransmission()
    - void allumeMoteur()
}

class Camion {
    - Remorque remorque
    + void roule()
    + void ChargeRemorque()
}

class Voiture {
}

Camion --|> Vehicule
Voiture --|> Vehicule
Conducteur -- Vehicule

@enduml