@startuml carte

(*) --> Recupere carte
if estUneCarteValide
--> analyse carte
if I < 16
    --> [oui] getCaracteresPositionI
    --> mutilplieLeCaraterePar2
    if nbCaratere > 9
    --> [oui] retire 9
    --> additionneCaracteresATmp
    else
    --> additionneCaracteresATmp
    endif
--> additionneProchainChiffrePairTmp
--> analyse carte
else
if TmpCommencePar0
--> affiche message correct
--> (*)
else
 --> affiche message incorrect
 --> (*)
else
--> affiche message incorrect
--> (*)
