@startuml encapsulation
scale 400*400

class Conducteur {
    + avance(Vehicule vehicule)
}

class Vehicule {
    + void roule()
    + void changeDirection(Direction direction)
    - void seConnectALArbreDeTransmission()
    - void allumeMoteur()
}

Conducteur -- Vehicule

@enduml