@startuml interface
scale 800*800

class Conducteur {
    + avance(Mobile mobile)
}

interface  Mobile {
    + void roule()
    + void changeDirection(Direction direction)
}

abstract class Vehicule {
    - void seConnectALArbreDeTransmission()
    - void allumeMoteur()
}

class Camion {
    - Remorque remorque
    + void ChargeRemorque()
}

class Voiture {
}

Camion --|> Vehicule
Voiture --|> Vehicule
Camion ..|> Mobile
Voiture ..|> Mobile
Velo ..|> Mobile
Conducteur -- Mobile

@enduml