@startuml interface2
scale 800*800

class Conducteur {
    + avance(Vehicule vehicule)
}

interface  Vehicule {
    + void roule()
    + void changeDirection(Direction direction)
}

class Camion {
    - Remorque remorque
    + void ChargeRemorque()
    - void seConnectALArbreDeTransmission()
    - void allumeMoteur()
}

class Voiture {
    - void seConnectALArbreDeTransmission()
    - void allumeMoteur()
}

Camion --|> Vehicule
Voiture --|> Vehicule
Conducteur -- Vehicule

@enduml