@startuml librairie
scale 800*800


class Livre {
  string nom
  string[] auteurs
  int nombrePages
}

class LivreScolaire {
  string discipline
  string niveau
}

class LivreEnfant {
  int ageMin
  int ageMax
}

Librairie "1" --o "*" Livre
LivreScolaire --|> Livre
LivreEnfant --|> Livre
@enduml