@startuml redefinition
scale 400*400

class Conducteur {
    + avance(Camion camion)
}

class Vehicule {
    + void roule()
    + void changeDirection(Direction direction)
    - void seConnectALArbreDeTransmission()
    - void allumeMoteur()
}

class Camion {
    - Remorque remorque
    + void roule()
    + void ChargeRemorque()
}

Camion --|> Vehicule
Conducteur -- Camion

@enduml