@startuml surcharge
scale 400*400

class Conducteur {
    + avance(Vehicule vehicule)
}


class Vehicule {
    + void roule()
    + void roule(int vitesse)
    + void changeDirection(Direction direction)
    - void seConnectALArbreDeTransmission()
    - void allumeMoteur()
}

Conducteur -- Vehicule

@enduml