@startuml vehicule
scale 600*600

class Vehicule {
    int numéro
    date dateDeFabrication
}

class Navire {
    byte pavillon
}

class Voilier {
    int hauteur
}

class Sousmarin {
    int nombreTorpilles
}

class Avion {
    int NombreDeRéacteurs
    int SuperficieDesAiles
}

Vehicule <|-- Avion
Vehicule <|-- Navire
Navire <|-- Voilier
Navire <|-- Sousmarin

@enduml