@startuml class

package app {
    package action {
        class actionTypes
        class connectivity
        class dashboard
        class downloads
        class favorites
        class github
        class githubContrib
        class helpers
        class importfavs
        class local
        class mastodon
        class player
        class playlists
        class plugins
        class queue
        class scrobbling
        class search
        class settings
        class tag
        class toasts
        class window
    }

    package components {
        class AlbumCover
        class Header
        class Playlists
        class AlbumList
        class HelpButton
        class PlaylistsSubMenu
        class AlbumView
        class HelpModal
        class PluginsView
        class ArtistList
        class LibraryView
        class SearchResults
        class ArtistView
        class ListeningHistoryView
        class Seekbar
        class Dashboard
        class LyricsView
        class Settings
        class Downloads
        class MainLayout
        class SidebarMenu
        class Equalizer
        class NavButtons
        class Spacer
        class EqualizerPresetList
        class Navbar
        class TagView
        class FavoriteAlbumsView
        class Normalizer
        class ToastComponent
        class FavoriteArtistsView
        class OauthPopup
        class TrackRow
        class FavoriteTracksView
        class PlayOptionsControls
        class TrackRowHeading
        class Footer
        class PlayQueue
        class VerticalPanel
        class HLSPlayer
        class PlaylistView
        class WindowControls
    }

    package constants {
        class propTypes
    }

    package containers {
        class AlbumViewContainer
        class PlaylistsContainer
        class ArtistViewContainer
        class PluginsContainer
        class BestNewMusicCardContainer
        class PromotedArtistsContainer
        class CommandPaletteContainer
        class QueuePopupButtons
        class DashboardContainer
        class QueuePopupContainer
        class DeezerPlaylistAdapter
        class SearchBoxContainer
        class DownloadsContainer
        class SearchResultsContainer
        class EqualizerViewContainer
        class SettingsContainer
        class ErrorBoundary
        class ShortcutsContainer
        class FavoritesContainer
        class SidebarMenuContainer
        class HelpModalContainer
        class SoundContainer
        class HttpApiUrl
        class SpotifyPlaylistImporter
        class IpcContainer
        class StreamVerificationContainer
        class LibraryViewContainer
        class TagViewContainer
        class ListeningHistoryContainer
        class ToastContainer
        class LyricsContainer
        class TrackPopupButtons
        class MainContentContainer
        class TrackPopupContainer
        class MiniPlayerContainer
        class TrackTableContainer
        class PlayQueueContainer
        class UserPanelContainer
        class PlayerBarContainer
        class VisualizerContainer
        class PlaylistViewContainer
    }

    package hoc {
        class withDropdownOptions
    }

    package hook {
        class useDispatchedCallback
        class useMastodonPost
        class usePlatform
    }

    package reducer {
        class connectivity
        class github
        class local
        class playlists
        class settings
        class dashboard
        class githubContrib
        class lyrics
        class plugins
        class tag
        class downloads
        class helpers
        class mastodon
        class queue
        class toasts
        class equalizer
        class importfavs
        class scrobbling
        class types
        class favorites
        class index
        class player
        class search
    }

    package rest {
        class Billboard
        class Github
    }

    package selector{
        class connectivity
        class githubContrib
        class mastodon
        class plugins
        class settings
        class dashboard
        class helpers
        class nuclear
        class queue
        class downloads
        class importfavs
        class player
        class scrobbling
        class favorites
        class lyrics
        class playlists
        class search
    }

    package store {
        class syncStorage
        class ipc
        class configureStore
    }

    package struct {
        class userPlugin
    }

    class App
    class globals
    class index
}

package core {
    package helpers {
        class index
        package playlist {
            class index
            class spotify
            class types
        }
    }
    package ipc {
        class events
    }
    package persistence {
        class store
    }
    package plugins {
        package lyrics {
            class azlyrics
            class index
            class simple
        }
        package meta {
            class audius
            class bandcamp
            class discogs
            class index
            class itunesmusic
            class itunespodcast
            class musicbrainz
        }
        package stream {
            class AudiusPlugin
            class BandcampPlugin
            class InvidiousPlugin
            class JamendoPlugin
            class SoundcloudPlugin
            class YoutubePlugin
            class iTunesPodcastPlugin
            class index

        }
        class api
        class config
        class lyricsProvider
        class metaProvider
        class plugin
        class streamProvider
        class transform
    }
    package rest-core {
        package nuclear-core {
            class Configuration
            class Identity
            class NuclearService
            class NuclearSupabaseService
            class Playlists
            class Promotion
            class StreamMappings
        }

        class Audius
        class CoverArtArchive
        class Lastfm
        class Musicbrainz
        class Soundcloud
        class Spotify
        class iTunes
        class Deezer
        class Invidious
        class SponsorBlock
        class Youtube
        class index
        class Bandcamp
        class Discogs
        class Jamendo
        class Mastodon
        class heuristics
    }

    class settings
    package structs {
        class Album
        class Artist
        class Track
    }
    class types
    package util {
        class index
        class retry
    }
    class index
}

package i18n {

}

package main {
    package controllers {
        class download
        class listening-history
        class local-library
        class logger
        class player
        class settings
    }

    package interfaces {
        class nuclear-api
    }
    package services {
        class linux
        class windows
        class config
        class download
        class ipc
        class local-library
        class platform
        class system-api
        class trayMenu
        class mac
        class acoustic-id
        class discord
        class http
        class listening-history
        class logger
        class store
        class touchbar
        class window
    }

    package utils {
        class container
        class decorators
        class env
        class tracks
        class types
    }
    class ioc
    class main
}

package ui {

}
@enduml