@startuml
left to right direction
actor User

package Nuclear {
    usecase "Create account" as createAccount
    usecase "Login account" as loginAccount
    usecase "Searching" as search
    usecase "For music" as searchMusic
    usecase "For album" as searchAlbum
    usecase "Browsing" as browsing
    usecase "By genre" as searchGenre
    usecase "By releases" as newestReleases
    usecase "By popularity" as searchPopularity
    usecase "Add music to queue" as addMusicQueue
    usecase "Load saved playlists" as load
    usecase "Scrobble status" as scrobble
    usecase "Enable radio mode" as radioMode
    usecase "Download music" as download
    usecase "Read lyrics" as lyrics
    usecase "Update favorite music" as favorites
    usecase "Update music source" as source
    usecase "Listen internet music" as internetMusic
    usecase "Listen local music" as localMusic
    usecase "Normalize music" as normalize
    usecase "Listen music" as listen
    usecase "Select music" as select
}


loginAccount --> load
loginAccount --> favorites

loginAccount --> scrobble

User --> createAccount
User --> loginAccount

User --> search
search --> searchMusic
search --> searchAlbum

User --> browsing
browsing --> searchGenre
browsing --> searchPopularity
browsing --> newestReleases

User --> select
select --> listen
select --> favorites
select --> download
select --> lyrics
select --> addMusicQueue
listen --> localMusic
listen --> internetMusic

User --> source
User --> radioMode
User --> normalize

@enduml